### ISSUE TITLE
Deprecated import

### ISSUE THREAD

**Issue by JamesEdgeley** [ExCALIBUR-NEPTUNE/NESO-Spack#30]
https://github.com/ExCALIBUR-NEPTUNE/NESO-Spack/blob/7487b7343e2cc15915af98596ae0a7490827966c/packages/stdpython/package.py#L12

`get_filetype`  was removed from spack as of this [change](https://github.com/spack/spack/pull/43114)

**Comment by cmacmackin** [comment]
To be honest, the entire stdpython package can be removed, I think. Pretty sure we don't use it for anything anymore.

**Comment by jwscook** [comment]
Could you make the PR for this please @JamesEdgeley ?
